-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTGfAuRKwskvrwB+z
Ad7zExI8PsD5NM/wboaevwNwyFmgCgYIKoZIzj0DAQehRANCAARxEUX2RYqpENvx
N5EKtCXRL6pjav01pPdVMPkGYpega8MzaBCuvTep1orB/ugv1XEL8gyNu6r+HoQn
RMoMViWf
-----END PRIVATE KEY-----